name: Deploy to ssh server

on:
  push:
    branches:
      - master

env:
  SSH_ADDRESS: justsell-front.maketest.it
  SSH_USER: js_test
  SSH_PORT: 22
  DEPLOY_FOLDER: /var/www/maketest.it/justsell-front/

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: unnecessary
      - name: Adding Known Hosts
        run: ssh-keyscan -p $SSH_PORT -H $SSH_ADDRESS  >> ~/.ssh/known_hosts
      #Setup yarn
      - run: yarn -v
      # Build
      - run: yarn install
      - run: yarn build
      # Deploy
      - run: cd dist && rsync -avz -e "ssh -p $SSH_PORT" --archive --compress --delete --progress --verbose . $SSH_USER@$SSH_ADDRESS:$DEPLOY_FOLDER
